### ISSUE TITLE
`map_num_in_range` scaling logic

### ISSUE THREAD

**Issue by cameronfyfe** [scottc11/ok-degree#89]
I randomly came across this while working another issue.  It looks like this function might be missing the offset for non-zero output minimums.  This is in the drivers repo which I don't think I have write access to so just posting this here.

Original/current:
```cpp
template <class T>
T map_num_in_range(T input, T minInput, T maxInput, T minOutput, T maxOutput)
{
    return ((float)(maxOutput - minOutput) / (maxInput - minInput)) * (input - minInput);
}
```

With output offset:
```cpp
template <class T>
T map_num_in_range(T input, T minInput, T maxInput, T minOutput, T maxOutput)
{
    return ((float)(maxOutput - minOutput) / (maxInput - minInput)) * (input - minInput) + minOutput;
}
```

You can also avoid converting from T to floating point and back to T and still retain the precision if you do the multiplication first.  The only concern here would be when using integer `T` types and if the multiplied value was going to surpass the max integer for `T`.

```cpp
template <class T>
T map_num_in_range(T input, T minInput, T maxInput, T minOutput, T maxOutput)
{
    return ((maxOutput - minOutput) * (input - minInput)) / (maxInput - minInput) + minOutput;
}
```

**Comment by scottc11** [comment]
> You can also avoid converting from T to floating point and back to T and still retain the precision if you do the multiplication first

@cameronfyfe would this save cpu cycles then?

**Comment by cameronfyfe** [comment]
@scottc11 Yeah it should save on the cpu cycles needed for `T -> float` as well as `float -> T` conversion at the end.  Avoiding floating point math should also save on a few cycles for sending values to the FPU registers and back since the integer math can just be done in MCU registers, but in general it's not crazy expensive to use floats on this chip since it has an FPU, so unless you are already seeing issues or really need to squeeze performance out of it, it probably doesn't matter too much

**Comment by cameronfyfe** [comment]
*just clarifying everything above is only relevant for `map_num_in_range<T>` when `T` is an integer type.  For `map_num_in_range<float>` it doesn't make a difference since it's already floating point.  I didn't look to see how it was actually being used everywhere

**Comment by scottc11** [comment]
@cameronfyfe  ok I see - yeah I will likely swap that out then
